apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: country-info-st-v1-pdb
  namespace: country-info
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: country-info-st-v1