apiVersion: v1
kind: Secret
metadata:
  name: country-info-secret
  namespace: country-info
  labels:
    app.kubernetes.io/name: country-info-st-v1
type: Opaque
stringData:
  DB_USERNAME: "<db_username>"
  DB_PASSWORD: "<db_password>"
