apiVersion: v1
kind: Service
metadata:
  name: country-info-st-v1
  namespace: country-info
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: country-info-st-v1
  ports:
    - name: http
      port: 80
      targetPort: http